# Configuração para desenvolvimento local
@baseUrl = http://localhost:3333

# Configuração para produção (Coolify)
# @baseUrl = https://api.umdoce.dev.br

###Health Check
GET {{baseUrl}}/health

###Root endpoint (debug)
GET {{baseUrl}}/

###Users

###Authentication

POST {{baseUrl}}/auth
Content-Type: application/json

{
    "name": "Felipe",
    "password": "123"
}

### Register

POST {{baseUrl}}/register
content-type: application/json

{
    "name": "Felipe",
    "password": "123"
}

###Recipes

### Create Recipe

POST {{baseUrl}}/recipes
content-type: application/json

{
    "name": "Bolo de Chocolate",
    "description": "Delicioso bolo de chocolate",
    "price": 25.50,
    "category": "Bolos"
}

### Get Recipes

GET {{baseUrl}}/recipes

###Orders

### Create Order

POST {{baseUrl}}/orders
content-type: application/json

{
    "idRecipe": "e030123c-ff85-4be6-b36b-03ea05d06253",
    "customerName": "Fjohn Doe",
    "quantity": 1,
    "status": "pending"
}

### Get Orders

GET {{baseUrl}}/orders/search?search=felipe

### Get Order by ID

GET {{baseUrl}}/orders/order-id-here

### Change Order Status

PATCH {{baseUrl}}/orders/order-id-here/status
content-type: application/json

{
    "status": "completed"
}

### Get Total Sales

GET {{baseUrl}}/orders/total

### Get Pending Sales

GET {{baseUrl}}/orders/total/pending

### Get Paid Sales

GET {{baseUrl}}/orders/total/paid

### Get Orders with Pagination

GET {{baseUrl}}/orders

### Fetch Previous Orders Last Week
GET {{baseUrl}}/orders/lastWeek

###
GET {{baseUrl}}/orders-by-date?date=2025-07-29